image: Visual Studio 2017
version: 0.4.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build:
- .paket\paket.exe restore
for:
  - branches:
      only:
        - master
    after_test:
      - .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%
  - branches:
      except:
        - master
    after_test:
      - .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_BRANCH%
artifacts:
  - path: '*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: lYIqcO230Ct+xY1Je+G17ImW6a3ZEHc1uBagpCQWdegbykpkCC3BB4QE0o+mF61/
  on:
    branch:
      - master

