image: Visual Studio 2017
version: 1.4.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: nuget restore src\MustardBlack.Html.Forms.sln
for:
  - branches:
      only:
        - master
    after_test:
      - dotnet pack src/MustardBlack.Html.Forms/MustardBlack.Html.Forms.csproj /property:PackageVersion=%APPVEYOR_BUILD_VERSION% /property:Configuration=Release
  - branches:
      except:
        - master
    after_test:
      - dotnet pack src/MustardBlack.Html.Forms/MustardBlack.Html.Forms.csproj /property:PackageVersion=%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_BRANCH% /property:Configuration=Release
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: AVvyXDEy8i8bEn7qLm571SoDvL4eFctkRSs1bwAgeY5zHxKPy8xxWE7CFrxkOu+W
  on:
    branch:
      - master

